name: Build Windows Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fix and sync submodules (HTTPS)
        run: |
          if (Test-Path .gitmodules) {
            (Get-Content .gitmodules) -replace 'git@github.com:', 'https://github.com/' | Set-Content .gitmodules
            git submodule sync
            git submodule update --init --recursive
          }

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install LLVM
        run: |
          choco install llvm -y

      - name: Setup Custom vcpkg
        shell: cmd
        run: |
          mkdir "%TEMP%\vcpkg" 2>nul
          cd C:\
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout 2023.04.15
          call bootstrap-vcpkg.bat

      - name: Install Dependencies (Manifest Mode)
        shell: cmd
        run: |
          C:\vcpkg\vcpkg.exe install --triplet x64-windows-static

      - name: Build RustDesk Client
        env:
          RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          LIBCLANG_PATH: 'C:\Program Files\LLVM\bin'
          VCPKG_ROOT: 'C:\vcpkg'
          VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
          # Variable clave para forzar a Clang a encontrar opus/opus_multistream.h
          BINDGEN_EXTRA_CLANG_ARGS: '-IC:\vcpkg\installed\x64-windows-static\include'
        run: |
          cargo build --release

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe
